name: Test

on:
  push:
    branches:
      - 'master'

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check format
        uses: psf/black@stable
        with:
          options: " -l 120 --check -t py311"
          src: "."
          version: "23.01"
